top_songs_2020 = [
    {"artist": "The Weeknd", "title": "Blinding Lights", "album": "After Hours", "image": "https://bit.ly/3o7XH7a", "year": 2020},
    {"artist": "Roddy Ricch", "title": "The Box", "album": "Please Excuse Me for Being Antisocial", "image": "https://bit.ly/3FpXWq7", "year": 2020},
    {"artist": "DaBaby ft. Roddy Ricch", "title": "ROCKSTAR", "album": "Blame It on Baby", "image": "https://bit.ly/3JaxUeK", "year": 2020},
    {"artist": "Dua Lipa", "title": "Don't Start Now", "album": "Future Nostalgia", "image": "https://bit.ly/3HpXbgz", "year": 2020},
    {"artist": "Post Malone", "title": "Circles", "album": "Hollywood's Bleeding", "image": "https://bit.ly/3HY6wJq", "year": 2020},
    {"artist": "Harry Styles", "title": "Watermelon Sugar", "album": "Fine Line", "image": "https://bit.ly/3MlF2vK", "year": 2020},
    {"artist": "Future ft. Drake", "title": "Life Is Good", "album": "High Off Life", "image": "https://bit.ly/3KAaMgg", "year": 2020},
    {"artist": "Maroon 5", "title": "Memories", "album": "Singles", "image": "https://bit.ly/3MaTfhn", "year": 2020},
    {"artist": "Lewis Capaldi", "title": "Someone You Loved", "album": "Divinely Uninspired to a Hellish Extent", "image": "https://bit.ly/3Ymi5Pq", "year": 2020},
    {"artist": "Billie Eilish", "title": "Everything I Wanted", "album": "Single", "image": "https://bit.ly/3KHIlJn", "year": 2020},
    {"artist": "Gabby Barrett ft. Charlie Puth", "title": "I Hope", "album": "Goldmine", "image": "https://bit.ly/3YlRZ9n", "year": 2020},
    {"artist": "Tones and I", "title": "Dance Monkey", "album": "The Kids Are Coming", "image": "https://bit.ly/3wDqfdJ", "year": 2020},
    {"artist": "Doja Cat", "title": "Say So", "album": "Hot Pink", "image": "https://bit.ly/3wGy5cR", "year": 2020},
    {"artist": "Megan Thee Stallion ft. Beyoncé", "title": "Savage Remix", "album": "Single", "image": "https://bit.ly/3JYQb8e", "year": 2020},
    {"artist": "Lady Gaga & Ariana Grande", "title": "Rain on Me", "album": "Chromatica", "image": "https://bit.ly/3KHJ3Kb", "year": 2020},
    {"artist": "BTS", "title": "Dynamite", "album": "BE", "image": "https://bit.ly/3EAh7nn", "year": 2020},
    {"artist": "Justin Bieber ft. Quavo", "title": "Intentions", "album": "Changes", "image": "https://bit.ly/3KJhIvh", "year": 2020},
    {"artist": "Arizona Zervas", "title": "Roxanne", "album": "Single", "image": "https://bit.ly/3JYTr2q", "year": 2020},
    {"artist": "Powfu ft. Beabadoobee", "title": "Death Bed (Coffee for Your Head)", "album": "Poems of the Past", "image": "https://bit.ly/3ZqVcUL", "year": 2020},
    {"artist": "Chris Brown & Young Thug", "title": "Go Crazy", "album": "Slime & B", "image": "https://bit.ly/3ZrPqXt", "year": 2020},
]

top_songs_2021 = [
    {"artist": "Olivia Rodrigo", "title": "drivers license", "album": "SOUR", "image": "https://bit.ly/3XH3jVy", "year": 2021},
    {"artist": "Lil Nas X", "title": "MONTERO (Call Me By Your Name)", "album": "MONTERO", "image": "https://bit.ly/3WACN7e", "year": 2021},
    {"artist": "The Kid LAROI & Justin Bieber", "title": "Stay", "album": "F*ck Love 3: Over You", "image": "https://bit.ly/3WdDn0E", "year": 2021},
    {"artist": "Dua Lipa", "title": "Levitating", "album": "Future Nostalgia", "image": "https://bit.ly/3XH8NOj", "year": 2021},
    {"artist": "BTS", "title": "Butter", "album": "Single", "image": "https://bit.ly/3wFbF9q", "year": 2021},
    {"artist": "Doja Cat ft. SZA", "title": "Kiss Me More", "album": "Planet Her", "image": "https://bit.ly/3wHCc7s", "year": 2021},
    {"artist": "Olivia Rodrigo", "title": "good 4 u", "album": "SOUR", "image": "https://bit.ly/3HKDw2f", "year": 2021},
    {"artist": "Justin Bieber", "title": "Peaches", "album": "Justice", "image": "https://bit.ly/3HKCrXs", "year": 2021},
    {"artist": "Adele", "title": "Easy On Me", "album": "30", "image": "https://bit.ly/3ZGu2Hu", "year": 2021},
    {"artist": "Silk Sonic", "title": "Leave The Door Open", "album": "An Evening with Silk Sonic", "image": "https://bit.ly/3Fq1OoP", "year": 2021},
    {"artist": "Masked Wolf", "title": "Astronaut In The Ocean", "album": "Astronomical", "image": "https://bit.ly/3WAFOrT", "year": 2021},
    {"artist": "Billie Eilish", "title": "Happier Than Ever", "album": "Happier Than Ever", "image": "https://bit.ly/3XDNVrN", "year": 2021},
    {"artist": "24kGoldn ft. iann dior", "title": "Mood", "album": "El Dorado", "image": "https://bit.ly/3JTYuPp", "year": 2021},
    {"artist": "The Weeknd", "title": "Save Your Tears", "album": "After Hours", "image": "https://bit.ly/3JUXcBP", "year": 2021},
    {"artist": "Drake ft. Future & Young Thug", "title": "Way 2 Sexy", "album": "Certified Lover Boy", "image": "https://bit.ly/3WYdPpK", "year": 2021},
    {"artist": "SZA", "title": "Good Days", "album": "Single", "image": "https://bit.ly/3ZN9s5s", "year": 2021},
    {"artist": "Kali Uchis", "title": "telepatía", "album": "Sin Miedo (del Amor y Otros Demonios)", "image": "https://bit.ly/3HZDhNO", "year": 2021},
    {"artist": "CJ", "title": "Whoopty", "album": "Single", "image": "https://bit.ly/3Fovx5r", "year": 2021},
    {"artist": "Lil Tjay ft. 6LACK", "title": "Calling My Phone", "album": "Destined 2 Win", "image": "https://bit.ly/3FniQoL", "year": 2021},
    {"artist": "Polo G", "title": "RAPSTAR", "album": "Hall of Fame", "image": "https://bit.ly/3FrH4H8", "year": 2021},
]

top_songs_2022 = [
    {"artist": "Harry Styles", "title": "As It Was", "album": "Harry's House", "image": "https://example.com/as_it_was.jpg", "year": 2022},
    {"artist": "Ed Sheeran", "title": "Bad Habits", "album": "Equals", "image": "https://example.com/bad_habits.jpg", "year": 2022},
    {"artist": "Glass Animals", "title": "Heat Waves", "album": "Dreamland", "image": "https://example.com/heat_waves.jpg", "year": 2022},
    {"artist": "Kate Bush", "title": "Running Up That Hill", "album": "Hounds of Love", "image": "https://example.com/running_up_that_hill.jpg", "year": 2022},
    {"artist": "Fireboy DML & Ed Sheeran", "title": "Peru", "album": "Apollo", "image": "https://example.com/peru.jpg", "year": 2022},
    {"artist": "LF System", "title": "Afraid to Feel", "album": "Single", "image": "https://example.com/afraid_to_feel.jpg", "year": 2022},
    {"artist": "Adele", "title": "Easy On Me", "album": "30", "image": "https://example.com/easy_on_me.jpg", "year": 2022},
    {"artist": "Elton John & Dua Lipa", "title": "Cold Heart (PNAU Remix)", "album": "The Lockdown Sessions", "image": "https://example.com/cold_heart.jpg", "year": 2022},
    {"artist": "Sam Fender", "title": "Seventeen Going Under", "album": "Seventeen Going Under", "image": "https://example.com/seventeen_going_under.jpg", "year": 2022},
    {"artist": "Belters Only ft. Jazzy", "title": "Make Me Feel Good", "album": "Single", "image": "https://example.com/make_me_feel_good.jpg", "year": 2022},
    {"artist": "Lizzo", "title": "About Damn Time", "album": "Special", "image": "https://example.com/about_damn_time.jpg", "year": 2022},
    {"artist": "Gayle", "title": "abcdefu", "album": "Single", "image": "https://example.com/abcdefu.jpg", "year": 2022},
    {"artist": "David Guetta, Becky Hill, Ella Henderson", "title": "Crazy What Love Can Do", "album": "Single", "image": "https://example.com/crazy_what_love_can_do.jpg", "year": 2022},
    {"artist": "Sam Smith & Kim Petras", "title": "Unholy", "album": "Gloria", "image": "https://example.com/unholy.jpg", "year": 2022},
    {"artist": "Taylor Swift", "title": "Anti-Hero", "album": "Midnights", "image": "https://example.com/anti_hero.jpg", "year": 2022},
    {"artist": "Steve Lacy", "title": "Bad Habit", "album": "Gemini Rights", "image": "https://example.com/bad_habit.jpg", "year": 2022},
    {"artist": "Lost Frequencies & Calum Scott", "title": "Where Are You Now", "album": "Single", "image": "https://example.com/where_are_you_now.jpg", "year": 2022},
    {"artist": "Fireboy DML", "title": "Bandana", "album": "Playboy", "image": "https://example.com/bandana.jpg", "year": 2022},
    {"artist": "George Ezra", "title": "Green Green Grass", "album": "Gold Rush Kid", "image": "https://example.com/green_green_grass.jpg", "year": 2022},
    {"artist": "Jack Harlow", "title": "First Class", "album": "Come Home the Kids Miss You", "image": "https://example.com/first_class.jpg", "year": 2022},
]

top_songs_2020_to_2022 = top_songs_2020 + top_songs_2021 + top_songs_2022
